/**
 * PlannerFw Library v4.0
 * Author: W3plan Technologies <https://www.w3plan.net/>
 * Copyright 2015-2020 W3plan Technologies
 * Code licensed under the GNU GPLv3 license <http://www.gnu.org/licenses/gpl.html>
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var m=0;return function(){return m<d.length?{done:!1,value:d[m++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,m,p){d!=Array.prototype&&d!=Object.prototype&&(d[m]=p.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(d,m){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:m})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function d(p){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(p||"")+"_"+m++,p)}var m=0;return d}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.asyncIterator;d||(d=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};
$jscomp.iteratorFromArray=function(d,m){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var p=0,r={next:function(){if(p<d.length){var y=p++;return{value:m(y,d[y]),done:!1}}r.next=function(){return{done:!0,value:void 0}};return r.next()}};r[Symbol.iterator]=function(){return r};return r};
$jscomp.polyfill=function(d,m,p,r){if(m){p=$jscomp.global;d=d.split(".");for(r=0;r<d.length-1;r++){var y=d[r];y in p||(p[y]={});p=p[y]}d=d[d.length-1];r=p[d];m=m(r);m!=r&&null!=m&&$jscomp.defineProperty(p,d,{configurable:!0,writable:!0,value:m})}};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
(function(){var d=function(){};d.outputMessage=function(b,c,f,h){f=f||0;h=h||"#000";"undefined"!=typeof pfConfig&&"production"==pfConfig.environment.toLowerCase()&&0!==b?d.consoleMessage(b,c,f,h):"undefined"!=typeof pfConfig&&"development"==pfConfig.environment.toLowerCase()&&3===b?d.consoleMessage(b,c,f,h):d.printMessage(b,c,f,h)};d.printMessage=function(b,c,f,h){f=f?" - Line: "+f:"";var d="",k=new Date;3==b||"string"==typeof b&&"notice"==b.toLowerCase()?d=k.getHours()+":"+k.getMinutes()+":"+k.getSeconds()+
"<strong> - Notice: </strong>"+c+f:2==b||"string"==typeof b&&"warning"==b.toLowerCase()?(d=k.getHours()+":"+k.getMinutes()+":"+k.getSeconds()+"<strong> - Warning: </strong>"+c+f,h="#ff00ff"):(d=k.getHours()+":"+k.getMinutes()+":"+k.getSeconds()+"<strong> - Error: <strong>"+c+f,h="#ff0000");b=document.createElement("div");b.innerHTML='<div style="margin-bottom:2px; padding:10px; background-color:#dddddd; color:'+h+'"><span style="margin-right:20px; color:#000; float:right; font-weight:bold; font-size:30px; line-height:20px; cursor:pointer;" onclick="this.parentElement.style.display=\'none\';">&times;</span>'+
d+"</div>";document.getElementsByTagName("body")[0]?document.getElementsByTagName("body")[0].insertBefore(b,document.getElementsByTagName("body")[0].firstChild):window.onload=function(){alert(d)}};d.consoleMessage=function(b,c,f,d){f=f?" - Line: "+f:"";var h=new Date;3==b||"string"==typeof b&&"notice"==b.toLowerCase()?console.log("%c "+h.getHours()+":"+h.getMinutes()+":"+h.getSeconds()+" - Notice:\n"+c+f,"color: "+d):2==b||"string"==typeof b&&"warning"==b.toLowerCase()?console.log("%c "+h.getHours()+
":"+h.getMinutes()+":"+h.getSeconds()+" - Warning:\n"+c+f,"color: "+d):console.log("%c "+h.getHours()+":"+h.getMinutes()+":"+h.getSeconds()+" - Error:\n"+c+f,"color: "+d)};var m=function(){};m.crc32=function(b,c){var f=-1;for(var d=0,q=b.length;d<q;d++){var k=(f^b.charCodeAt(d))&255;k="0x"+"00000000 77073096 EE0E612C 990951BA 076DC419 706AF48F E963A535 9E6495A3 0EDB8832 79DCB8A4 E0D5E91E 97D2D988 09B64C2B 7EB17CBD E7B82D07 90BF1D91 1DB71064 6AB020F2 F3B97148 84BE41DE 1ADAD47D 6DDDE4EB F4D4B551 83D385C7 136C9856 646BA8C0 FD62F97A 8A65C9EC 14015C4F 63066CD9 FA0F3D63 8D080DF5 3B6E20C8 4C69105E D56041E4 A2677172 3C03E4D1 4B04D447 D20D85FD A50AB56B 35B5A8FA 42B2986C DBBBC9D6 ACBCF940 32D86CE3 45DF5C75 DCD60DCF ABD13D59 26D930AC 51DE003A C8D75180 BFD06116 21B4F4B5 56B3C423 CFBA9599 B8BDA50F 2802B89E 5F058808 C60CD9B2 B10BE924 2F6F7C87 58684C11 C1611DAB B6662D3D 76DC4190 01DB7106 98D220BC EFD5102A 71B18589 06B6B51F 9FBFE4A5 E8B8D433 7807C9A2 0F00F934 9609A88E E10E9818 7F6A0DBB 086D3D2D 91646C97 E6635C01 6B6B51F4 1C6C6162 856530D8 F262004E 6C0695ED 1B01A57B 8208F4C1 F50FC457 65B0D9C6 12B7E950 8BBEB8EA FCB9887C 62DD1DDF 15DA2D49 8CD37CF3 FBD44C65 4DB26158 3AB551CE A3BC0074 D4BB30E2 4ADFA541 3DD895D7 A4D1C46D D3D6F4FB 4369E96A 346ED9FC AD678846 DA60B8D0 44042D73 33031DE5 AA0A4C5F DD0D7CC9 5005713C 270241AA BE0B1010 C90C2086 5768B525 206F85B3 B966D409 CE61E49F 5EDEF90E 29D9C998 B0D09822 C7D7A8B4 59B33D17 2EB40D81 B7BD5C3B C0BA6CAD EDB88320 9ABFB3B6 03B6E20C 74B1D29A EAD54739 9DD277AF 04DB2615 73DC1683 E3630B12 94643B84 0D6D6A3E 7A6A5AA8 E40ECF0B 9309FF9D 0A00AE27 7D079EB1 F00F9344 8708A3D2 1E01F268 6906C2FE F762575D 806567CB 196C3671 6E6B06E7 FED41B76 89D32BE0 10DA7A5A 67DD4ACC F9B9DF6F 8EBEEFF9 17B7BE43 60B08ED5 D6D6A3E8 A1D1937E 38D8C2C4 4FDFF252 D1BB67F1 A6BC5767 3FB506DD 48B2364B D80D2BDA AF0A1B4C 36034AF6 41047A60 DF60EFC3 A867DF55 316E8EEF 4669BE79 CB61B38C BC66831A 256FD2A0 5268E236 CC0C7795 BB0B4703 220216B9 5505262F C5BA3BBE B2BD0B28 2BB45A92 5CB36A04 C2D7FFA7 B5D0CF31 2CD99E8B 5BDEAE1D 9B64C2B0 EC63F226 756AA39C 026D930A 9C0906A9 EB0E363F 72076785 05005713 95BF4A82 E2B87A14 7BB12BAE 0CB61B38 92D28E9B E5D5BE0D 7CDCEFB7 0BDBDF21 86D3D2D4 F1D4E242 68DDB3F8 1FDA836E 81BE16CD F6B9265B 6FB077E1 18B74777 88085AE6 FF0F6A70 66063BCA 11010B5C 8F659EFF F862AE69 616BFFD3 166CCF45 A00AE278 D70DD2EE 4E048354 3903B3C2 A7672661 D06016F7 4969474D 3E6E77DB AED16A4A D9D65ADC 40DF0B66 37D83BF0 A9BCAE53 DEBB9EC5 47B2CF7F 30B5FFE9 BDBDF21C CABAC28A 53B39330 24B4A3A6 BAD03605 CDD70693 54DE5729 23D967BF B3667A2E C4614AB8 5D681B02 2A6F2B94 B40BBE37 C30C8EA1 5A05DF1B 2D02EF8D".substr(9*
k,8);f=f>>>8^k}b=(f^-1)>>>0;return c&&10==c?b:b.toString(16)};var p=function(){var b=0,c="",f="",h="",q=null,k=!1,n=!1,u=null,g=[],t=[],A=function(){return Date.now?Date.now():(new Date).getTime()},m=function(a,e,w,n){e=e.toLowerCase();var l=a.substring(0,a.indexOf("?")),g=a.substring(a.indexOf("?")+1);l||(l=a,g="");var c=new XMLHttpRequest;"post"==e?(c.open("POST",l,!0),c.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8")):"put"==e?(c.open("PUT",l,!0),c.setRequestHeader("Content-type",
"application/x-www-form-urlencoded; charset=UTF-8")):"delete"==e?(c.open("DELETE",l,!0),c.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8")):(!n&&g?a=l+"?"+g+"&_="+A():n||g||(a=l+"?_="+A()),c.open("GET",a,!0));c.setRequestHeader("X-Requested-With","ModelXMLHttpRequest");c.responseType="text";c.timeout=w;"post"==e||"put"==e||"delete"==e?c.send(g):c.send();return c},w=function(a){return/^(ftp:|ftps:|ws:|wss:|http:|https:)?\/\//i.test(a)&&(a=a.split("/")[2].toLowerCase(),
a=a.split(":")[0],a!=window.location.hostname.toLowerCase())?!1:!0},v=function(a){return/^\s*<([\s\S]*)>\s*$/g.test(a)&&/<pfDataSet>([\s\S]*?)<\/pfDataSet>/g.test(a)?"XML":"JSON"},a=function(){throw Error("Template can't be loaded, checking the template path");},z=function(a){for(var l={},e=[],w=[],c=[],n=[],b,u,f,d=0,k=a.length;d<k;d++)b=a[d],"string"===typeof b&&4<b.length?(b=planner.adaptTemplatePath(b),e.push(b.replace(/&/g,"%26")),-1!==b.indexOf("?tm=")&&(b=b.substring(0,b.indexOf("?tm="))),
g.push(planner.lexicrc32(b))):Array.isArray(b)&&2===b.length&&(f=b[1],"[object Object]"===Object.prototype.toString.call(f)&&(f=JSON.stringify(f)),b=planner.adaptTemplatePath(b[0]),w.push(b.replace(/&/g,"%26")),-1!==b.indexOf("?tm=")&&(b=b.substring(0,b.indexOf("?tm="))),u=planner.lexicrc32(b),c.push(u+b.replace(/&/g,"%26")),n.push(encodeURIComponent(f)),t.push(u));0<e.length&&(l.tmWithVoid=e);0<w.length&&(l.tmWithVal=w);0<c.length&&(l.tmField=c);0<n.length&&""!==n.join("~~").replace(/~/g,"")&&(l.mdField=
n);return l},e=function(a){var l=g,e=t;if("undefined"!==typeof pfTemplateFailed&&pfTemplateFailed)throw pfTemplateFailed=null,Error("The controller can't load template");if(a.hasOwnProperty("modelDataFailed")&&"string"===typeof a.modelDataFailed&&0<a.modelDataFailed.length)throw a.modelDataFailed="",Error("The controller can't load modeldata");if("string"===typeof a&&"WOMODEL"==a){a=0;for(e=l.length;a<e;a++){var b=l[a];document.getElementById(b).innerHTML=window[b].run()}g=[]}else{planner.checkModelData(a);
for(var w=0,c=e.length;w<c;w++)b=e[w],l=a.pfDataSet[b],planner.validateSdjs(l),document.getElementById(b).innerHTML=window[b].run(l);t=[]}};this.minimizeCode=function(a){return a.replace(/[\t\n\r]/g," ").replace(/\/\*((?!\*\/).)*\*\//g,"").replace(/ {2,}/g," ").replace(/> +</g,"><").replace(/\{ +/g,"{").replace(/ +\}/g,"}").trim()};this.isPfTemplate=function(a){var l=!1,e;for(e in a)if(a.hasOwnProperty(e)){if("function"===typeof a[e]&&a[e].constructor===Function){if("run"==e&&!/\s*\.replace\(\/\\\\'\/g, *"'"\)\s*\.replace\(\/\\\\v\/g, *"\\\\'"\);\s*}\s*$/i.test(a.run.toString()))return!1}else return!1;
l=!0}return l?!0:!1};this.responseJsonEncode=function(a){if("string"===typeof a)try{a=this.minimizeCode(a),a=JSON.parse(a)}catch(x){throw Error("Data isn't a JSON string, "+x.message);}if(a&&"object"===typeof a&&0<Object.keys(a).length)return a;throw Error("Data isn't JSON");};this.getModeldataType=function(a){return v(a)};this.checkModelData=function(a){if("undefined"===typeof a||!a||!a.hasOwnProperty("pfDataSet")||1>Object.keys(a).length)throw Error("Modeldata is invalid");return!0};this.adaptTemplatePath=
function(a){a=decodeURIComponent(a).trim();a=a.replace(/\\/g,"/").replace(/\/$/g,"");-1!==a.indexOf("/tmpl/")&&(a=a.substring(a.indexOf("/tmpl/")+5));return"/"+a.replace(/^(tmpl\/|\/)/i,"")};this.updateSegments=function(a){if(Array.isArray(a)&&0<a.length){window.onerror=function(a,e,b,w,c){d.outputMessage(0,a,b)};if(!pfConfig)throw Error("You have to load planner-setting.js along with planner.js");a=z(a);a.hasOwnProperty("tmWithVoid")&&this.loadTemplate(pfConfig.environment,pfConfig.templateTimeout,
pfConfig.templateGateway+"?___="+a.tmWithVoid.join("~~"),e,"WOMODEL");a.hasOwnProperty("tmWithVal")&&(this.loadTemplate(pfConfig.environment,pfConfig.templateTimeout,pfConfig.templateGateway+"?___="+a.tmWithVal.join("~~"),e),a.hasOwnProperty("mdField")?this.loadModelData(pfConfig.environment,pfConfig.modeldataTimeout,pfConfig.modeldataGateway+"?___="+a.tmField.join("~~")+"&md="+a.mdField.join("~~"),"GET",e):this.loadModelData(pfConfig.environment,pfConfig.modeldataTimeout,pfConfig.modeldataGateway+
"?___="+a.tmField.join("~~"),"GET",e))}};this.loadTemplate=function(e,b,c,g,d){d=d||"";var l=!1;if(w(c)){if(f!==c){"production"!==e.toLowerCase()&&(c+="&_="+A());k=!1;var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src=c;t.addEventListener("error",a);t.onerror=a;setTimeout(function(){if(!l)throw Error("Request template timeout");},b);t.readyState?t.onreadystatechange=function(){if("loaded"==t.readyState||"complete"==t.readyState)l=!0,t.onreadystatechange=null,g&&"function"===
typeof g&&d?g(d):g&&"function"===typeof g&&n?(g(u),f="",n=k=!1,u=null):(k=!0,f=c,pfConfig.trackExecutedTime&&(q=new Date,h="tm"))}:t.onload=function(){l=!0;g&&"function"===typeof g&&d?g(d):g&&"function"===typeof g&&n?(g(u),f="",n=k=!1,u=null):(k=!0,f=c,pfConfig.trackExecutedTime&&(q=new Date,h="tm"))};(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(t)}}else throw Error("Cross-origin template request blocked");};this.loadModelData=function(a,e,b,c,g){c=
c||"get";var l=!1;"production"==a.toLowerCase()&&(l=!0);if(w(b)){n=!1;var d=m(b,c,e,l);d.onreadystatechange=function(){if(4==d.readyState)if(200<=d.status&&300>d.status||-1!=[301,304,404].indexOf(d.status))if("XML"==v(d.responseText)){var a=planner.string2Xml(d.responseText);a=planner.xml2Json(a);var e=Object.keys(a)[0];g&&"function"===typeof g&&k?(g(a[e]),f="",n=k=!1):(n=!0,u=a[e],pfConfig.trackExecutedTime&&(q=new Date,h="md"))}else a=planner.responseJsonEncode(d.responseText),g&&"function"===typeof g&&
k?(g(a),f="",n=k=!1):(n=!0,u=a,pfConfig.trackExecutedTime&&(q=new Date,h="md"));else throw Error("Failed to access the modeldata");};d.onerror=function(){throw Error("Error to access the modeldata");};d.ontimeout=function(){throw Error("Modeldata request timeout");}}else throw Error("Cross-origin modeldata request blocked");};this.setCookie=function(a,e,b,c){b=b||"";c=c||"/";document.cookie=a+"="+encodeURIComponent(e)+"; expires="+b+"; path="+c};this.getCookie=function(a){a+="=";for(var e=document.cookie.split(";"),
b=0,c=e.length;b<c;b++){for(var g=e[b];" "==g.charAt(0);)g=g.substring(1,g.length);if(0===g.indexOf(a)){a=g.substring(a.length,g.length);try{return decodeURIComponent(a)}catch(D){return a}}}return null};this.deleteCookie=function(a,e){document.cookie=a+"=;expires=Thu, 01 Jan 1970 00:00:01 GMT; path="+(e||"/")};this.startMeter=function(){return new Date};this.getElapsedTime=function(a){return"Total elapsed time: "+(new Date-a)+" [milliseconds]"};this.getElapsedDetailTime=function(a){var e=c.split("."),
b=+e[0]+ +e[1]+ +e[2];if(3===e.length){if(q&&0<h.length){if("tm"==h){a=q-a-+e[0];var g=+e[1]}else g=q-a-+e[0],a=+e[1];h="";q=null;a="ms \n2. Getting template ready: "+a+"ms \n   Getting modeldata ready: "+g}else a=pfConfig.trackExecutedTime?"ms \n2. Getting template ready: "+e[1]:"ms \n2. Getting template and modeldata ready: "+e[1];b="\n1. Checking environment and parse the url: "+e[0]+a+"ms \n3. Rendering page: "+e[2]+"ms \n\nTotal elapsed time: "+b+"ms"}return b};this.updateTrackTime=function(a,
e){a?(a=new Date-a,c=e?c+("."+(a-b)):c+((c?".":"")+(a-b)),b=a):(b=0,c="")}},r=function(){var b=function(b,f){if(!b||!b.trim())return"";f=f||"";8>f.length&&(f="8q2EXsYBCDZcK3hajFFnyzdGRTbnrYbjYJzkbMFfRJFdvhPfBmpNVw2YkBZtM9kLW6MRAst7Vb3yh8KZwq2dTNuVdq8acHYeavBaPz3MPsBGpAP3zaCDvZUTvNGaWvpNwqwnQ9D8nZ8T4K9D8HRyQ2XTapaAeDSUfanvkCkRFzh4vSs3C9qBWxTwx9PUTTrAaL5PfgvQRWaCtCAZng3P8S9aEYEST79w2Ryu5Vs4etvKz4xdM8K7uCn2yFZ5C2MJ");var c=b.length;f=f.split("");for(var d=f.length,k="",n=0;n<c;n++){var u=b.charCodeAt(n)^
f[n%d].charCodeAt(0);k+=String.fromCharCode(u)}return k};this.pfEncode=function(c,f){f=f||"";try{var h=encodeURIComponent(c);h=b(h,f);h=window.btoa(h);return encodeURIComponent(h)}catch(q){d.outputMessage(2,"Encryption failed, "+q.message)}};this.pfDecode=function(c,f){f=f||"";try{var h=decodeURIComponent(c);h=window.atob(h);h=b(h,f);return decodeURIComponent(h)}catch(q){d.outputMessage(2,"Decryption failed, "+q.message)}};this.crc32CheckSum=function(b,d){return m.crc32(b,d)};this.lexicrc32=function(b){b=
"/"+b.replace(/^\s+|\s+$/g,"").replace(/\\/g,"/").replace(/^\/|\/$/g,"").replace(/\.[^/.]+$/,"").toLowerCase();return"pf"+m.crc32(b,16).replace("-","")}},y=function(){var b="% cm in mm pc pt ch em ex gd px rem vh vw vm deg grad rad turn s ms hz khz vmin vmax".split(" "),c=function(b){b=b.trim();var c=b.replace("#",""),g=b.match(/^#[0-9a-f]+/i);return!g||b!=g[0]||3!==c.length&&6!==c.length?!1:!0},f={},h=function(b,c){c=c||"";for(var g in b)if("object"==typeof b[g]){var d=c;d=(d=d.trim())?d+" ":"";
d+=g.trim();d=-1!==g.indexOf(",")?q(c,g.trim()):d.replace(/ +&|& +/g,"").trim();f[d]=f[d]||[];h(b[g],d)}else f[c][f[c].length]="  "+g.trim()+": "+b[g].trim()+"\r\n"},q=function(b,c){return c.split(",").map(function(c){var g=" ";""===c.trim()&&(g="");return(b.trim()+g+c.trim()).replace(/ +&|& +/g,"")}).join(",")},k=function(b,c){return c.split(",").map(function(c){var g=" ";""===c.trim()&&(g="");return(c.trim()+g+b.trim()).replace(/ +&|& +/g,"")}).join(",")};this.prefixSelectors=function(b,c){return q(b,
c)};this.suffixSelectors=function(b,c){return k(b,c)};this.parseNestedCss=function(b,c){c=c||{minified:!1};b=("{"+b+"}").replace(/\\\r\\\n|\\\r|\\\n|\r\n|\r|\n|\t/g," ").replace(/ {2,}/g," ").replace(/"/g,"'").replace(/:([^:;\{}]+)}/g,":$1;}").replace(/:([^:;\{}]+);/g,':"$1;",').replace(/",([^",:\{}]+):"/g,'","$1":"').replace(/\{([^:",;\{}]+):"/g,'{"$1":"').replace(/}([^:",;\{}]+):"/g,'},"$1":"').replace(/;",([^;"\{}]+)\{/g,';","$1":{').replace(/}([^;"\{}]+)\{/g,'},"$1":{').replace(/\{([^;"\{}]+)\{/g,
'{"$1":{').replace(/,( )*}/g,"}").replace(/\{([^;"\{}]+)\{/g,'{"$1":{');b=JSON.parse(b);f={};h(b);b="";for(g in f)f[g]!=[]&&f[g].join("")&&(b+=g+" {\r\n",b+=f[g].join(""),b+="}\r\n\r\n");var g=b;c.minified&&(g=g.replace(/[\t\r\n]/g," ").replace(/\/\*((?!\*\/).)*\*\//g,"").replace(/ {2,}/g," ").replace(/{ +/g,"{").replace(/; }/g,";}"));return g.trim()};this.rgb2HexColor=function(b){var c=1;-1!==b.indexOf("%")&&(b=b.replace(/%/g,""),c=2.55);var g=b.match(/^(rgb|rgba)?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*/i);
if(g&&5===g.length){var d=parseInt(g[2]*c,10),f=parseInt(g[3]*c,10);c=parseInt(g[4]*c,10);if(256>d&&256>f&&256>c)return"#"+("0"+d.toString(16)).slice(-2)+("0"+f.toString(16)).slice(-2)+("0"+c.toString(16)).slice(-2)}return b};this.hexColor2Rgb=function(b){if(c(b)){var d=b.replace("#","");3==d.length&&(d=d[0]+d[0]+d[1]+d[1]+d[2]+d[2]);var g=parseInt(d.substr(0,2),16),f=parseInt(d.substr(2,2),16);d=parseInt(d.substr(4,2),16);if(256>g&&256>f&&256>d)return"rgb("+g+", "+f+", "+d+")"}return b};this.hexColor2Rgba=
function(b,d){if(c(b)){var g=b.replace("#","");3==g.length&&(g=g[0]+g[0]+g[1]+g[1]+g[2]+g[2]);var f=parseInt(g.substr(0,2),16),k=parseInt(g.substr(2,2),16);g=parseInt(g.substr(4,2),16);if(256>f&&256>k&&256>g&&0<=d&&1>=d)return"rgba("+f+", "+k+", "+g+", "+d+")"}return b};this.stripCssUnit=function(b){return b.toString().replace(/%|cm|in|mm|pc|pt|ch|em|ex|gd|px|rem|vh|vw|vm|deg|grad|rad|turn|s|ms|hz|khz|vmin|vmax| +|;/ig,"")};this.addCssUnit=function(c,f){f=f||"px";if(-1==b.indexOf(f))return d.outputMessage(2,
"PFCSS can not process the unit"),c;c=+c;return 0===c%1?c+f:c.toFixed(6).replace(/^0+/,"").replace(/0+$/,"")+f}},B=function(){var b=function(b){return Number(b)===b&&0===b%1},c=function(b){return Number(b)===b&&0!==b%1},d=function(b){return"number"===typeof b&&!isNaN(b)},h=function(b){return"string"===typeof b&&!isNaN(b)&&b==+b},q=function(b){return h(b)&&/e\+|-/gi.test(b)},k=function(b){return h(b)&&/^-?0x[0-9a-f]+$/i.test(b)},n=function(b){return h(b)&&/^-?0[0-7]+$/i.test(b)},u=function(b){for(var c in b)if(b.hasOwnProperty(c))return!1;
return!0},g=function(b){return"string"===typeof b||b instanceof String},t=function(b){return"[object Object]"===Object.prototype.toString.call(b)},m=function(c,f,a,k){var e=[],l;for(l in c)"enumeration"==l?Array.isArray(c.enumeration)&&-1!==c.enumeration.indexOf(a)?e.push(1):e.push(0):"pattern"==l?g(a)&&"[object RegExp]"===Object.prototype.toString.call(new RegExp(a))&&c.pattern.test(a)?e.push(1):e.push(0):"length"==l?b(a)&&a.length===c.length?e.push(1):e.push(0):"maxLength"==l?b(a)&&a.length<=c.maxLength?
e.push(1):e.push(0):"minLength"==l?b(a)&&a.length>=c.minLength?e.push(1):e.push(0):"totalDigits"==l?d(a)&&a.toString().repalce(".","").length===c.totalDigits&&0<c.totalDigits?e.push(1):e.push(0):"fractionDigits"==l?d(a)&&a.toString().split(".")[1].length===c.fractionDigits?e.push(1):e.push(0):"minExclusive"==l?d(a)&&a>c.minExclusive?e.push(1):e.push(0):"maxExclusive"==l?d(a)&&a<c.maxExclusive?e.push(1):e.push(0):"minInclusive"==l?d(a)&&a>=c.minInclusive?e.push(1):e.push(0):"maxInclusive"==l&&(d(a)&&
a<=c.maxInclusive?e.push(1):e.push(0));if(0<e.length&&-1===e.indexOf(0))return!0;f==k&&(f="");throw Error("The value "+a+" of "+k+" member "+f+" againsts constraint "+JSON.stringify(c));},p=function(f,v,a,z){var e=!1;switch(f){case "string":g(a)&&(e=!0);break;case "emptyString":g(a)&&!a&&(e=!0);break;case "numberString":h(a)&&(e=!0);break;case "integerString":g(a)&&b(+a)&&(e=!0);break;case "floatString":g(a)&&c(+a)&&(e=!0);break;case "fractionString":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(e=!0);break;
case "exponentString":q(a)&&(e=!0);break;case "asciiString":"string"===typeof a&&/^[\x00-\xFF]+$/.test(a)&&(e=!0);break;case "hexString":k(a)&&(e=!0);break;case "octalString":n(a)&&(e=!0);break;case "jsonString":try{JSON.parse(a)}catch(l){throw v==z&&(v=""),Error("The value "+a+" of "+z+" member "+v+" againsts type: "+f);}e=!0;break;case "normalizedString":h(a)&&a.replace(/[\t\r\n]/g,"")==a&&(e=!0);break;case "regExpString":g(a)&&"[object RegExp]"===Object.prototype.toString.call(new RegExp(a))&&
(e=!0);break;case "url":/^(ftp:|ftps:|ws:|wss:|http:|https:)?(\/\/)((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(:\d+)?(\/[-a-z\d%_.~+=]*)*(\?[;&a-z\d%_.~+=-]*)?(#[-a-z\d_]*)?$/i.test(a)&&(e=!0);break;case "urlEncoded":encodeURIComponent(decodeURIComponent(a))===a&&(e=!0);break;case "email":/^(?=.{1,254}$)(?=.{1,64}@)[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+(\.[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+)*@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/.test(a)&&
(e=!0);break;case "ipv4":/^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(a)&&(e=!0);break;case "base64":try{window.atob(a)}catch(l){throw v==z&&(v=""),Error("The value "+a+" of "+z+" member "+v+" against type: "+f);}e=!0;break;case "uuid":/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$/.test(a)&&(e=!0);break;case "unicodeString":"string"===typeof a&&/[^\u0000-\u10FFFF]+$/.test(a)&&(e=!0);break;case "country":-1!=="AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI KH CM CA CV KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MK MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SZ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW".split(" ").indexOf(a.trim().toUpperCase())&&
(e=!0);break;case "language":/^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$/.test(a)&&(e=!0);break;case "cssString":/^(?:\s*[\S ]+\s*{[^}]*})+/.test(a)&&(e=!0);break;case "hexColor":/^#([a-f0-9]{3}){1,2}$/i.test(a)&&(e=!0);break;case "rgbColor":/^rgb(a)?\(\d{1,3},\s?\d{1,3},\s?\d{1,3}\)$/i.test(a)&&(e=!0);break;case "cssRatio":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(e=!0);break;case "cssLength":!g(a)||-1==="ch em ex rem vh vw px mm cm in pt pc".split(" ").indexOf(a.trim().slice(-2).toLowerCase())&&
-1===["vmin","vmax"].indexOf(a.trim().slice(-4).toLowerCase())||(e=!0);break;case "cssAngle":!g(a)||-1===["deg","rad"].indexOf(a.trim().slice(-3).toLowerCase())&&-1===["grad","turn"].indexOf(a.trim().slice(-4).toLowerCase())||(e=!0);break;case "cssResolution":!g(a)||-1===["dpcm","dppx"].indexOf(a.trim().slice(-4).toLowerCase())&&"dpi"!==a.trim().slice(-3).toLowerCase()||(e=!0);break;case "cssFrequency":!g(a)||"hz"!==a.trim().slice(-2).toLowerCase()&&"khz"!==a.trim().slice(-3).toLowerCase()||(e=!0);
break;case "cssTime":!g(a)||"s"!==a.trim().slice(-1).toLowerCase()&&"ms"!==a.trim().slice(-2).toLowerCase()||(e=!0);break;case "cssPercentage":g(a)&&"%"===a.trim().slice(-1).toLowerCase()&&(e=!0);break;case "cssPosition":-1!==["static","relative","absolute","sticky","fixed"].indexOf(a.trim().toLowerCase())&&(e=!0);break;case "date":"string"===typeof a&&!isNaN(new Date(a))&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(e=!0);break;case "time":g(a)&&/^([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&
(e=!0);break;case "dateTime":g(a)&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01]) ([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&(e=!0);break;case "gYear":g(a)&&/^\d{4}$/.test(a)&&(e=!0);break;case "gMonth":g(a)&&/^--(0[1-9]|1[012])--$/.test(a)&&(e=!0);break;case "gDay":g(a)&&/^---(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(e=!0);break;case "gYearMonth":g(a)&&/^\d{4}-(0[1-9]|1[012])$/.test(a)&&(e=!0);break;case "gMonthDay":g(a)&&/^--(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&
(e=!0);break;case "integer":b(a)&&(e=!0);break;case "float":c(a)&&(e=!0);break;case "exponent":d(a)&&/^e\+|-/i.test(a)&&(e=!0);break;case "zero":d(a)&&0===a&&(e=!0);break;case "positiveInteger":b(a)&&0<a&&(e=!0);break;case "nonNegativeInteger":b(a)&&0<=a&&(e=!0);break;case "negativeInteger":b(a)&&0>a&&(e=!0);break;case "nonPositiveInteger":b(a)&&0>=a&&(e=!0);break;case "positiveFloat":c(a)&&0<a&&(e=!0);break;case "nonNegativeFloat":c(a)&&0<=a&&(e=!0);break;case "negativeFloat":c(a)&&0>a&&(e=!0);break;
case "nonPositiveFloat":c(a)&&0>=a&&(e=!0);break;case "finiteNumber":isFinite(a)&&(e=!0);break;case "number":d(a)&&(e=!0);break;case "true":"boolean"===typeof a&&!0===a&&(e=!0);break;case "false":"boolean"===typeof a&&!1===a&&(e=!0);break;case "boolean":"boolean"===typeof a&&(e=!0);break;case "null":null===a&&(e=!0);break;case "emptyObject":u(a)&&(e=!0);break;case "serializeObject":t(a)&&(e=!0);break;case "emptyArray":Array.isArray(a)&&0===a.length&&(e=!0);break;case "stringArray":Array.isArray(a)&&
a.every(function(a){return g(a)})&&(e=!0);break;case "positiveIntegerArray":Array.isArray(a)&&a.every(function(a){return b(a)&&0<a})&&(e=!0);break;case "nonNegativeIntegerArray":Array.isArray(a)&&a.every(function(a){return b(a)&&0<=a})&&(e=!0);break;case "negativeIntegerArray":Array.isArray(a)&&a.every(function(a){return b(a)&&0>a})&&(e=!0);break;case "integerArray":Array.isArray(a)&&a.every(function(a){return b(a)})&&(e=!0);break;case "numberArray":Array.isArray(a)&&a.every(function(a){return d(a)})&&
(e=!0);break;case "array":Array.isArray(a)&&(e=!0)}if(e)return!0;v==z&&(v="");throw Error("The value "+a+" of "+z+" member "+v+" againsts type: "+f);};this.validateSdjs=function(b,c){c=c||{};for(var a in b)if(b.hasOwnProperty(a))if("_pfGlobal"===a&&t(b._pfGlobal)&&(c=b._pfGlobal),t(b[a]))this.validateSdjs(b[a],c);else if(Array.isArray(b[a]))for(var d=0,e=b[a].length;d<e;d++)if(t(b[a][d])||Array.isArray(b[a][d]))this.validateSdjs(b[a][d],c);else{if(b.hasOwnProperty(a+"_pfidx")){var f=null;b[a+"_pfidx"].hasOwnProperty("all")&&
"undefined"!==typeof b[a+"_pfidx"].all.type?f="all":b[a+"_pfidx"].hasOwnProperty("i"+d)&&"undefined"!==typeof b[a+"_pfidx"]["i"+d].type&&(f="i"+d);null!==f&&(p(b[a+"_pfidx"][f].type,d,b[a][d],a),"undefined"!==typeof b[a+"_pfidx"][f].constraint&&m(b[a+"_pfidx"][f].constraint,d,b[a][d],a))}}else b.hasOwnProperty(a+"_pfsch")&&g(b[a+"_pfsch"])&&""!==b[a+"_pfsch"]&&c.hasOwnProperty(a+"_"+b[a+"_pfsch"])&&"undefined"!==typeof c[a+"_"+b[a+"_pfsch"]].type?(p(c[a+"_"+b[a+"_pfsch"]].type,a,b[a],a),"undefined"!==
typeof c[a+"_"+b[a+"_pfsch"]].constraint&&m(c[a+"_"+b[a+"_pfsch"]].constraint,a,b[a],a)):b.hasOwnProperty(a+"_pfsch")&&"undefined"!==typeof b[a+"_pfsch"].type?(p(b[a+"_pfsch"].type,a,b[a],a),"undefined"!==typeof b[a+"_pfsch"].constraint&&m(b[a+"_pfsch"].constraint,a,b[a],a)):6<a.length&&"_pfsch"===a.slice(-6)&&"implied"===b[a].presence&&"undefined"!==typeof b[a].type&&!b.hasOwnProperty(a.slice(0,-6))&&(d="",e=null,b.hasOwnProperty(a.slice(0,-6)+"_default")?(d=a.slice(0,-6)+"_default",e=b[d]):b.hasOwnProperty(a.slice(0,
-6)+"_fixed")&&(d=a.slice(0,-6)+"_fixed",e=b[d]),null!==e&&(p(b[a].type,d,e,a),"undefined"!==typeof b[a].constraint&&m(b[a].constraint,d,e,a)))}},C=function(){var b=[],c={toString:function(){return"null"},valueOf:function(){return null}},d=function(b){return/^\s*$/.test(b)?null:/^(?:true|false)$/i.test(b)?"true"===b.toLowerCase():isFinite(b)?parseFloat(b):b},h=function(f,n,u){var g=b.length,k=f.hasChildNodes(),q=!!(n&2),m,p=0,v="",a=q?{}:"";var r=f.hasAttributes?f.hasAttributes():!1;if(k){var e=0;
for(m=f.childNodes.length;e<m;e++){var l=f.childNodes.item(e);4===l.nodeType?v+=l.nodeValue:3===l.nodeType?v+=l.nodeValue.trim():1===l.nodeType&&b.push(l)}}e=b.length;l=d(v);q||!k&&!r||(a=0===n?null===l?c:l instanceof Object?l:new l.constructor(l):{});for(var x=g;x<e;x++)k=b[x].nodeName,m=h(b[x],n,u),a.hasOwnProperty(k)?(a[k].constructor!==Array&&(a[k]=[a[k]]),a[k].push(m)):(a[k]=m,p++);if(r){r=f.attributes?f.attributes.length:0;k=u?"":"_";e=u?{}:a;for(x=0;x<r;p++,x++)m=f.attributes.item(x),e[k+m.name]=
d(m.value.trim());u&&(a.keyAttrs=e,p-=r-1)}3===n||(2===n||1===n&&0<p)&&v?a.keyVal=l:!q&&0===p&&v&&(a=l);"object"===typeof a&&0===Object.getOwnPropertyNames(a).length&&(a="");"string"===typeof a&&"null"==a.toLowerCase()&&(a=null);b.length=g;return a},q=function(b,c,d){if(d.constructor===String||d.constructor===Number||d.constructor===Boolean){if(c.appendChild(b.createTextNode(d.toString())),d===d.valueOf())return}else d.constructor===Date&&c.appendChild(b.createTextNode(d.toGMTString()));for(var g in d)if(d.hasOwnProperty(g)){var f=
d[g];if(!(isFinite(g)||f instanceof Function))if("keyVal"===g)null!==f&&!0!==f&&c.appendChild(b.createTextNode(f.constructor===Date?f.toGMTString():String(f)));else if("keyAttrs"===g)for(var k in f)f.hasOwnProperty(k)&&c.setAttribute(k,f[k]);else if("_"===g.charAt(0))c.setAttribute(g.slice(1),f);else if(f.constructor===Array)for(var h=0,n=f.length;h<n;h++){var m=b.createElement(g);q(b,m,f[h]);c.appendChild(m)}else m=b.createElement(g),f instanceof Object?q(b,m,f):null!==f&&!0!==f&&m.appendChild(b.createTextNode(f.toString())),
c.appendChild(m)}};this.xml2Json=function(b,c,d){var f=1<arguments.length&&"number"===typeof c?c&3:1;return h(b,f,2<arguments.length?d:3===f)};this.json2Xml=function(b,c,d,f){c=document.implementation.createDocument(c||null,d||"",f||null);q(c,c,b);return c};this.string2Xml=function(b){return(new window.DOMParser).parseFromString(b,"application/xml")};this.xml2String=function(b){return"undefined"!==typeof b.xml?b.xml:(new XMLSerializer).serializeToString(b)}};window.planner=new function(b){p.apply(this,
arguments);r.apply(this,arguments);y.apply(this,arguments);B.apply(this,arguments);C.apply(this,arguments);this.TITLE="PlannerFw Library "+b;this.DESCRIPTION="PlannerFw JavaScript Library, "+b;this.EDITION="Exec";this.VERSION=b;this.COPYRIGHT="Copyright 2015-"+(new Date).getFullYear()+" W3plan Technologies";window.name="PlannerFw "+b;this.section=function(b,d){return""};this.checkEnvironment=function(){if(!window.JSON||"function"!==typeof window.JSON.parse)throw Error("Your browser doesn't support JSON");
if(!window.XMLHttpRequest)throw Error("Your browser doesn't support XMLHttpRequest");pfConfig||alert("Failed to load planner-setting.js")};this.errorHandler=function(b,f,h){d.outputMessage(b,f,h||0)}}("Version 4.0");String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.indexOf||(Array.prototype.indexOf=function(b,c){void 0===c&&(c=0);0>c&&(c+=this.length);0>c&&(c=0);for(var d=this.length;c<d;c++)if(c in this&&this[c]===b)return c;return-1});
Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(b,c){void 0===c&&(c=this.length-1);0>c&&(c+=this.length);c>this.length-1&&(c=this.length-1);for(c++;0<c--;)if(c in this&&this[c]===b)return c;return-1});Array.prototype.every||(Array.prototype.every=function(b,c){var d=this.length;c=c?c:void 0;for(var h=0;h<d;h++)if(!b.call(c,this[h],h,this))return!1;return!0});Array.prototype.map||(Array.prototype.map=function(b){for(var c=[],d=0;d<this.length;d++)c.push(b(this[d],d,this));return c});
Array.isArray||(Array.isArray=function(b){return"[object Array]"===Object.prototype.toString.call(b)});window.btoa||(window.btoa=function(b){var c=0,d=0,h=[];if(!b)return b;b+="";do{var m=b.charCodeAt(c++);var k=b.charCodeAt(c++);var n=b.charCodeAt(c++);var p=m<<16|k<<8|n;m=p>>18&63;k=p>>12&63;n=p>>6&63;p&=63;h[d++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)}while(c<b.length);c=h.join("");b=b.length%3;return(b?c.slice(0,b-3):c)+"===".slice(b||3)});window.atob||(window.atob=function(b){var c=0,d=0,h=[];if(!b)return b;b+="";do{var m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(c++));var k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(c++));var n="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(c++));
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(c++));var g=m<<18|k<<12|n<<6|p;m=g>>16&255;k=g>>8&255;g&=255;64==n?h[d++]=String.fromCharCode(m):64==p?h[d++]=String.fromCharCode(m,k):h[d++]=String.fromCharCode(m,k,g)}while(c<b.length);return h.join("").replace(/\0+$/,"")});window.console||(window.console={});window.console.log||(window.console.log=function(){})})();
