/**
 * Self-Description JSON Schema v1.2.1
 * Author: W3plan Technologies <https://www.w3plan.net/>
 * Copyright 2015-2020 W3plan Technologies
 * Code licensed under MIT License
 */
(function(){var m=function(){};m.printMessage=function(d,e,f,g){f=f||0;g=g||"#000";f=f?" - Line: "+f:"";var h="",l=new Date;3==d||"string"==typeof d&&"notice"==d.toLowerCase()?h=l.getHours()+":"+l.getMinutes()+":"+l.getSeconds()+"<strong> - Notice: </strong>"+e+f:2==d||"string"==typeof d&&"warning"==d.toLowerCase()?(h=l.getHours()+":"+l.getMinutes()+":"+l.getSeconds()+"<strong> - Warning: </strong>"+e+f,g="#ff00ff"):(h=l.getHours()+":"+l.getMinutes()+":"+l.getSeconds()+"<strong> - Error: <strong>"+
e+f,g="#ff0000");d=document.createElement("div");d.innerHTML='<div style="margin-bottom:2px; padding:10px; background-color:#dddddd; color:'+g+'"><span style="margin-right:20px; color:#000; float:right; font-weight:bold; font-size:30px; line-height:20px; cursor:pointer;" onclick="this.parentElement.style.display=\'none\';">&times;</span>'+h+"</div>";document.getElementsByTagName("body")[0]?document.getElementsByTagName("body")[0].insertBefore(d,document.getElementsByTagName("body")[0].firstChild):
window.onload=function(){alert(h)}};m.consoleMessage=function(d,e,f,g){f=f||0;g=g||"#000";f=f?" - Line: "+f:"";var h=new Date;3==d||"string"==typeof d&&"notice"==d.toLowerCase()?console.log("%c "+h.getHours()+":"+h.getMinutes()+":"+h.getSeconds()+" - Notice:\n"+e+f,"color: "+g):2==d||"string"==typeof d&&"warning"==d.toLowerCase()?console.log("%c "+h.getHours()+":"+h.getMinutes()+":"+h.getSeconds()+" - Warning:\n"+e+f,"color: "+g):console.log("%c "+h.getHours()+":"+h.getMinutes()+":"+h.getSeconds()+
" - Error:\n"+e+f,"color: "+g)};var w=function(){var d=function(c){return Number(c)===c&&0===c%1},e=function(c){return Number(c)===c&&0!==c%1},f=function(c){return"number"===typeof c&&!isNaN(c)},g=function(c){return"string"===typeof c&&!isNaN(c)&&c==+c},h=function(c){return g(c)&&/e\+|-/gi.test(c)},l=function(c){return g(c)&&/^-?0x[0-9a-f]+$/i.test(c)},v=function(c){return g(c)&&/^-?0[0-7]+$/i.test(c)},p=function(c){for(var d in c)if(c.hasOwnProperty(d))return!1;return!0},k=function(c){return"string"===
typeof c||c instanceof String},t=function(c,e,a,g){var b=[],n;for(n in c)"enumeration"==n?Array.isArray(c.enumeration)&&-1!==c.enumeration.indexOf(a)?b.push(1):b.push(0):"pattern"==n?k(a)&&"[object RegExp]"===Object.prototype.toString.call(new RegExp(a))&&c.pattern.test(a)?b.push(1):b.push(0):"length"==n?d(a)&&a.length===c.length?b.push(1):b.push(0):"maxLength"==n?d(a)&&a.length<=c.maxLength?b.push(1):b.push(0):"minLength"==n?d(a)&&a.length>=c.minLength?b.push(1):b.push(0):"totalDigits"==n?f(a)&&
a.toString().repalce(".","").length===c.totalDigits&&0<c.totalDigits?b.push(1):b.push(0):"fractionDigits"==n?f(a)&&a.toString().split(".")[1].length===c.fractionDigits?b.push(1):b.push(0):"minExclusive"==n?f(a)&&a>c.minExclusive?b.push(1):b.push(0):"maxExclusive"==n?f(a)&&a<c.maxExclusive?b.push(1):b.push(0):"minInclusive"==n?f(a)&&a>=c.minInclusive?b.push(1):b.push(0):"maxInclusive"==n&&(f(a)&&a<=c.maxInclusive?b.push(1):b.push(0));if(0<b.length&&-1===b.indexOf(0))return!0;e==g&&(e="");m.printMessage(2,
"The value "+a+" of "+g+" member "+e+" againsts constraint "+JSON.stringify(c));return!1},u=function(c,q,a,r){var b=!1;switch(c){case "string":k(a)&&(b=!0);break;case "emptyString":k(a)&&!a&&(b=!0);break;case "numberString":g(a)&&(b=!0);break;case "integerString":k(a)&&d(+a)&&(b=!0);break;case "floatString":k(a)&&e(+a)&&(b=!0);break;case "fractionString":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(b=!0);break;case "exponentString":h(a)&&(b=!0);break;case "asciiString":"string"===typeof a&&/^[\x00-\xFF]+$/.test(a)&&
(b=!0);break;case "hexString":l(a)&&(b=!0);break;case "octalString":v(a)&&(b=!0);break;case "jsonString":try{JSON.parse(a)}catch(n){q==r&&(q=""),m.printMessage(2,"The value "+a+" of "+r+" member "+q+" againsts type: "+c),b=!1}b=!0;break;case "normalizedString":g(a)&&a.replace(/[\t\r\n]/g,"")==a&&(b=!0);break;case "regExpString":k(a)&&"[object RegExp]"===Object.prototype.toString.call(new RegExp(a))&&(b=!0);break;case "url":/^(ftp:|ftps:|ws:|wss:|http:|https:)?(\/\/)((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(:\d+)?(\/[-a-z\d%_.~+=]*)*(\?[;&a-z\d%_.~+=-]*)?(#[-a-z\d_]*)?$/i.test(a)&&
(b=!0);break;case "urlEncoded":encodeURIComponent(decodeURIComponent(a))===a&&(b=!0);break;case "email":/^(?=.{1,254}$)(?=.{1,64}@)[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+(\.[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+)*@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/.test(a)&&(b=!0);break;case "ipv4":/^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(a)&&(b=!0);break;case "base64":try{window.atob(a)}catch(n){q==r&&(q=""),m.printMessage(2,
"The value "+a+" of "+r+" member "+q+" against type: "+c),b=!1}b=!0;break;case "uuid":/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$/.test(a)&&(b=!0);break;case "unicodeString":"string"===typeof a&&/[^\u0000-\u10FFFF]+$/.test(a)&&(b=!0);break;case "country":-1!=="AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI KH CM CA CV KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MK MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SZ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW".split(" ").indexOf(a.trim().toUpperCase())&&
(b=!0);break;case "language":/^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$/.test(a)&&(b=!0);break;case "cssString":/^(?:\s*[\S ]+\s*{[^}]*})+/.test(a)&&(b=!0);break;case "hexColor":/^#([a-f0-9]{3}){1,2}$/i.test(a)&&(b=!0);break;case "rgbColor":/^rgb(a)?\(\d{1,3},\s?\d{1,3},\s?\d{1,3}\)$/i.test(a)&&(b=!0);break;case "cssRatio":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(b=!0);break;case "cssLength":!k(a)||-1==="ch em ex rem vh vw px mm cm in pt pc".split(" ").indexOf(a.trim().slice(-2).toLowerCase())&&
-1===["vmin","vmax"].indexOf(a.trim().slice(-4).toLowerCase())||(b=!0);break;case "cssAngle":!k(a)||-1===["deg","rad"].indexOf(a.trim().slice(-3).toLowerCase())&&-1===["grad","turn"].indexOf(a.trim().slice(-4).toLowerCase())||(b=!0);break;case "cssResolution":!k(a)||-1===["dpcm","dppx"].indexOf(a.trim().slice(-4).toLowerCase())&&"dpi"!==a.trim().slice(-3).toLowerCase()||(b=!0);break;case "cssFrequency":!k(a)||"hz"!==a.trim().slice(-2).toLowerCase()&&"khz"!==a.trim().slice(-3).toLowerCase()||(b=!0);
break;case "cssTime":!k(a)||"s"!==a.trim().slice(-1).toLowerCase()&&"ms"!==a.trim().slice(-2).toLowerCase()||(b=!0);break;case "cssPercentage":k(a)&&"%"===a.trim().slice(-1).toLowerCase()&&(b=!0);break;case "cssPosition":-1!==["static","relative","absolute","sticky","fixed"].indexOf(a.trim().toLowerCase())&&(b=!0);break;case "date":"string"===typeof a&&!isNaN(new Date(a))&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(b=!0);break;case "time":k(a)&&/^([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&
(b=!0);break;case "dateTime":k(a)&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01]) ([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&(b=!0);break;case "gYear":k(a)&&/^\d{4}$/.test(a)&&(b=!0);break;case "gMonth":k(a)&&/^--(0[1-9]|1[012])--$/.test(a)&&(b=!0);break;case "gDay":k(a)&&/^---(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(b=!0);break;case "gYearMonth":k(a)&&/^\d{4}-(0[1-9]|1[012])$/.test(a)&&(b=!0);break;case "gMonthDay":k(a)&&/^--(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&
(b=!0);break;case "integer":d(a)&&(b=!0);break;case "float":e(a)&&(b=!0);break;case "exponent":f(a)&&/^e\+|-/i.test(a)&&(b=!0);break;case "zero":f(a)&&0===a&&(b=!0);break;case "positiveInteger":d(a)&&0<a&&(b=!0);break;case "nonNegativeInteger":d(a)&&0<=a&&(b=!0);break;case "negativeInteger":d(a)&&0>a&&(b=!0);break;case "nonPositiveInteger":d(a)&&0>=a&&(b=!0);break;case "positiveFloat":e(a)&&0<a&&(b=!0);break;case "nonNegativeFloat":e(a)&&0<=a&&(b=!0);break;case "negativeFloat":e(a)&&0>a&&(b=!0);break;
case "nonPositiveFloat":e(a)&&0>=a&&(b=!0);break;case "finiteNumber":isFinite(a)&&(b=!0);break;case "number":f(a)&&(b=!0);break;case "true":"boolean"===typeof a&&!0===a&&(b=!0);break;case "false":"boolean"===typeof a&&!1===a&&(b=!0);break;case "boolean":"boolean"===typeof a&&(b=!0);break;case "null":null===a&&(b=!0);break;case "emptyObject":p(a)&&(b=!0);break;case "serializeObject":isObject(a)&&(b=!0);break;case "emptyArray":Array.isArray(a)&&0===a.length&&(b=!0);break;case "stringArray":Array.isArray(a)&&
a.every(function(a){return k(a)})&&(b=!0);break;case "positiveIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0<a})&&(b=!0);break;case "nonNegativeIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0<=a})&&(b=!0);break;case "negativeIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0>a})&&(b=!0);break;case "integerArray":Array.isArray(a)&&a.every(function(a){return d(a)})&&(b=!0);break;case "numberArray":Array.isArray(a)&&a.every(function(a){return f(a)})&&
(b=!0);break;case "array":Array.isArray(a)&&(b=!0)}if(b)return!0;q==r&&(q="");m.printMessage(2,"The value "+a+" of "+r+" member "+q+" againsts type: "+c);return!1};this.validateSdjs=function(c,e){e=e||{};for(var a in c)if(c.hasOwnProperty(a))if("_pfGlobal"===a&&isObject(c._pfGlobal)&&(e=c._pfGlobal),isObject(c[a]))this.validateSdjs(c[a],e);else if(Array.isArray(c[a]))for(var d=0,b=c[a].length;d<b;d++)if(isObject(c[a][d])||Array.isArray(c[a][d]))this.validateSdjs(c[a][d],e);else{if(c.hasOwnProperty(a+
"_pfidx")){var f=null;c[a+"_pfidx"].hasOwnProperty("all")&&"undefined"!==typeof c[a+"_pfidx"].all.type?f="all":c[a+"_pfidx"].hasOwnProperty("i"+d)&&"undefined"!==typeof c[a+"_pfidx"]["i"+d].type&&(f="i"+d);null!==f&&(u(c[a+"_pfidx"][f].type,d,c[a][d],a),"undefined"!==typeof c[a+"_pfidx"][f].constraint&&t(c[a+"_pfidx"][f].constraint,d,c[a][d],a))}}else c.hasOwnProperty(a+"_pfsch")&&k(c[a+"_pfsch"])&&""!==c[a+"_pfsch"]&&e.hasOwnProperty(a+"_"+c[a+"_pfsch"])&&"undefined"!==typeof e[a+"_"+c[a+"_pfsch"]].type?
(u(e[a+"_"+c[a+"_pfsch"]].type,a,c[a],a),"undefined"!==typeof e[a+"_"+c[a+"_pfsch"]].constraint&&t(e[a+"_"+c[a+"_pfsch"]].constraint,a,c[a],a)):c.hasOwnProperty(a+"_pfsch")&&"undefined"!==typeof c[a+"_pfsch"].type?(u(c[a+"_pfsch"].type,a,c[a],a),"undefined"!==typeof c[a+"_pfsch"].constraint&&t(c[a+"_pfsch"].constraint,a,c[a],a)):6<a.length&&"_pfsch"===a.slice(-6)&&"implied"===c[a].presence&&"undefined"!==typeof c[a].type&&!c.hasOwnProperty(a.slice(0,-6))&&(d="",b=null,c.hasOwnProperty(a.slice(0,-6)+
"_default")?(d=a.slice(0,-6)+"_default",b=c[d]):c.hasOwnProperty(a.slice(0,-6)+"_fixed")&&(d=a.slice(0,-6)+"_fixed",b=c[d]),null!==b&&(u(c[a].type,d,b,a),"undefined"!==typeof c[a].constraint&&t(c[a].constraint,d,b,a)))}};window.sdjs=new function(d){w.apply(this,arguments);this.TITLE="Self-Description JSON Schema";this.DESCRIPTION="The JavaScript Library for JSON description and constraints";this.VERSION=d;this.COPYRIGHT="Copyright "+(new Date).getFullYear()+" W3plan Technologies";this.checkJsonSupport=
function(){if(!window.JSON||"function"!==typeof window.JSON.parse)throw Error("Your browser doesn't support JSON");};this.boxMessage=function(d,f,g){m.printMessage(d,f,g||"")};this.consoleMessage=function(d,f,g,h){m.consoleMessage(d,f,g||"",h||"")}}("Version 1.1.0");String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.indexOf||(Array.prototype.indexOf=function(d,e){void 0===e&&(e=0);0>e&&(e+=this.length);0>e&&(e=0);for(var f=this.length;e<
f;e++)if(e in this&&this[e]===d)return e;return-1});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(d,e){void 0===e&&(e=this.length-1);0>e&&(e+=this.length);e>this.length-1&&(e=this.length-1);for(e++;0<e--;)if(e in this&&this[e]===d)return e;return-1});Array.prototype.every||(Array.prototype.every=function(d,e){var f=this.length;e=e?e:void 0;for(var g=0;g<f;g++)if(!d.call(e,this[g],g,this))return!1;return!0});Array.prototype.map||(Array.prototype.map=function(d){for(var e=[],f=
0;f<this.length;f++)e.push(d(this[f],f,this));return e});Array.isArray||(Array.isArray=function(d){return"[object Array]"===Object.prototype.toString.call(d)});window.btoa||(window.btoa=function(d){var e=0,f=0,g=[];if(!d)return d;d+="";do{var h=d.charCodeAt(e++);var l=d.charCodeAt(e++);var m=d.charCodeAt(e++);var p=h<<16|l<<8|m;h=p>>18&63;l=p>>12&63;m=p>>6&63;p&=63;g[f++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)}while(e<d.length);e=g.join("");d=d.length%3;return(d?e.slice(0,d-3):e)+"===".slice(d||3)});window.atob||(window.atob=function(d){var e=0,f=0,g=[];if(!d)return d;d+="";do{var h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));
var m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var k=h<<18|l<<12|m<<6|p;h=k>>16&255;l=k>>8&255;k&=255;64==m?g[f++]=String.fromCharCode(h):64==p?g[f++]=String.fromCharCode(h,l):g[f++]=String.fromCharCode(h,l,k)}while(e<d.length);return g.join("").replace(/\0+$/,"")});window.console||(window.console={});window.console.log||(window.console.log=function(){})})();
